// Angles — 16-bit circular, 65536 brads = 2π, π = 32768 (22-DECISIONS.md
// D1). This unit is deliberately different from the Q16.16 trig return
// scale (65536 = 1.0); conflating them is a spec violation, not a style
// choice.
//
// wrapToPi is the reorient idea kept from the predecessor (legacy/01
// § 4.3): angles are a wrapped quantity and wrapping them is a real
// operation, normalised into (−π, π] — so −π maps to +π and a heading is
// always a single canonical integer.
//
// fsin / fcos / fatan2 are the DSL's trig (09 § 2.2), fixed lookup tables
// per 10-DETERMINISM.md § 2.2 (4096 entries per quadrant). 20 § 4.3 places
// the tables in the math module; angle.ts owns them because their input is
// a brad angle. Tables are built once at module load by integer CORDIC —
// the committed constants below are the only real-number approximation in
// the pipeline, and no float ever exists at runtime (the web/ determinism
// lint enforces it). Measured quality, pinned by tests: fsin within 21
// Q16.16 units of the real sine (≈ 0.0003), fatan2 within 6 brads (≈ 0.03°)
// with exact results at every axis and diagonal.

import { assertInteger } from './fixed';

declare const angleBrand: unique symbol;

export type Angle = number & { readonly [angleBrand]: true };

export const BRADS_PER_TURN = 65536;
const HALF_TURN = 32768;
const QUARTER_TURN = 16384;

export const ANGLE_PI: Angle = 32768 as Angle;

// Accepts any integer heading — including unbounded accumulators — and
// normalises into (−π, π]. Every Angle in circulation satisfies that
// invariant because this is the only constructor.
export function wrapToPi(raw: number): Angle {
  assertInteger(raw, 'angle');
  let wrapped = raw % BRADS_PER_TURN;
  if (wrapped > HALF_TURN) {
    wrapped -= BRADS_PER_TURN;
  } else if (wrapped <= -HALF_TURN) {
    wrapped += BRADS_PER_TURN;
  }
  return wrapped as Angle;
}

// Signed shortest path from `from` to `to`: turning 179° → −179° yields
// +2°, not 358° (23-WEB-CLIENT-PLAN.md § 4, 1.2). At exact antipodes the
// result is +π — both directions are equally short and the positive one is
// the canonical choice.
export function angleDiff(from: Angle, to: Angle): Angle {
  return wrapToPi(to - from);
}

// Unsigned smallest angle between two headings, in [0, π].
export function angleBetween(a: Angle, b: Angle): Angle {
  const diff = angleDiff(a, b);
  return (diff < 0 ? -diff : diff) as Angle;
}

// ---------------------------------------------------------------------------
// Fixed trig tables (10-DETERMINISM.md § 2.2), built once at module load
// ---------------------------------------------------------------------------

const QUARTER_ENTRIES = 4096;
// 16384 brads spanned by one quadrant, so one entry steps 4 brads.
const BRADS_PER_ENTRY = 4;
// One table entry spans 16 Q16.16 ratio units (65536 / 4096).
const Q16_PER_ENTRY = 16;

// brads of atan(2^-i) for i = 0..13 — ANG[13] is the last ≥ 1 brad, so more
// iterations cannot move a brad-angle result. Generated by
// scripts/gen-cordic-constants.py alongside the measured error bounds.
const CORDIC_ANG: readonly number[] = [
  8192, 4836, 2555, 1297, 651, 326, 163, 81, 41, 20, 10, 5, 3, 1,
];
// Q16.16 of 1 / 1.6467602540313 — the 14-iteration CORDIC gain, so the
// rotated vector keeps radius 65536.
const CORDIC_GAIN_Q16 = 39797;

// Rotation mode: rotate (GAIN, 0) into `target` brads, return the Q16.16
// y — the sine. Load-time only; every runtime read is a table lookup.
function cordicSin(target: number): number {
  let x = CORDIC_GAIN_Q16;
  let y = 0;
  let accumulated = 0;
  for (let i = 0; i < CORDIC_ANG.length; i++) {
    const step = accumulated < target ? 1 : -1;
    const dy = y >> i;
    const dx = x >> i;
    if (step > 0) {
      x -= dy;
      y += dx;
      accumulated += CORDIC_ANG[i] as number;
    } else {
      x += dy;
      y -= dx;
      accumulated -= CORDIC_ANG[i] as number;
    }
  }
  if (y < 0) return 0;
  if (y > BRADS_PER_TURN) return BRADS_PER_TURN;
  return y;
}

// Vectoring mode: the brad angle of (x, y) for y ≥ 0, driving y to zero.
// Load-time only — it builds the atan table.
function cordicAngleOf(x: number, y: number): number {
  let accumulated = 0;
  for (let i = 0; i < CORDIC_ANG.length; i++) {
    if (y > 0) {
      const dy = y >> i;
      const dx = x >> i;
      x += dy;
      y -= dx;
      accumulated -= CORDIC_ANG[i] as number;
    } else if (y < 0) {
      const dy = y >> i;
      const dx = x >> i;
      x -= dy;
      y += dx;
      accumulated += CORDIC_ANG[i] as number;
    }
  }
  return -accumulated;
}

// Magnitudes of sin over [0, π/2]; entry i covers 4i brads. The two
// boundary entries are definitional (sin 0 = 0, sin π/2 = 1), not
// approximations, so the quadrant pins are exact.
const SIN_TABLE: ReadonlyArray<number> = (() => {
  const table = Array.from({ length: QUARTER_ENTRIES + 1 }, (_, entry) =>
    cordicSin(entry * BRADS_PER_ENTRY),
  );
  table[0] = 0;
  table[QUARTER_ENTRIES] = BRADS_PER_TURN;
  return table;
})();

// brads of atan over the ratios i/4096, i = 0..4096 — the first quadrant's
// lower octant. Vectoring probes (65536, 16i), whose slope is i/4096.
const ATAN_TABLE: ReadonlyArray<number> = (() => {
  const probeX = BRADS_PER_TURN;
  const probeYStep = BRADS_PER_TURN / QUARTER_ENTRIES;
  const table = Array.from({ length: QUARTER_ENTRIES + 1 }, (_, entry) =>
    cordicAngleOf(probeX, entry * probeYStep),
  );
  table[0] = 0;
  table[QUARTER_ENTRIES] = QUARTER_TURN / 2;
  return table;
})();

// |sin| of a heading in [0, 65536), folding the four quadrants onto the
// table: odd quadrants mirror around π/2, the upper half negates. The
// input snaps to the NEAREST entry — rounding halves the quantisation
// error a truncating fold would pay at the steep small-angle slope.
function sinMagnitude(wrapped: number): number {
  const quadrant = (wrapped >> 14) & 3;
  const inQuad = wrapped & (QUARTER_TURN - 1);
  const snapped =
    (quadrant & 1) === 1 ? QUARTER_TURN - inQuad : inQuad;
  return SIN_TABLE[(snapped + BRADS_PER_ENTRY / 2) / BRADS_PER_ENTRY | 0] as number;
}

// Q16.16 sine (65536 = 1.0) of a brad angle. Exact at 0, ±π/2 and ±π.
export function fsin(angle: number): number {
  assertInteger(angle, 'angle');
  const wrapped = ((angle % BRADS_PER_TURN) + BRADS_PER_TURN) % BRADS_PER_TURN;
  const magnitude = sinMagnitude(wrapped);
  if (magnitude === 0) return 0;
  return (wrapped >> 14) >= 2 ? -magnitude : magnitude;
}

// Q16.16 cosine (65536 = 1.0): a phase shift of π/2 onto the same table.
export function fcos(angle: number): number {
  assertInteger(angle, 'angle');
  const shifted = angle + QUARTER_TURN;
  const wrapped = ((shifted % BRADS_PER_TURN) + BRADS_PER_TURN) % BRADS_PER_TURN;
  const magnitude = sinMagnitude(wrapped);
  if (magnitude === 0) return 0;
  return (wrapped >> 14) >= 2 ? -magnitude : magnitude;
}

// The Q16.16 ratio min/max as an integer in [0, 65536]; BigInt because the
// shift up overflows int32 for near-full-scale coordinates.
function ratioQ16(small: number, large: number): number {
  return Number((BigInt(small) << 16n) / BigInt(large));
}

// Brad angle of (dy, dx) in (−π, π], matching wrapToPi's canonical range.
// Exact at both axes and all four diagonals; 0 for the zero vector, which
// has no heading (the same convention as vec2.angleOf).
export function fatan2(dy: number, dx: number): number {
  assertInteger(dy, 'dy');
  assertInteger(dx, 'dx');
  if (dy === 0 && dx === 0) return 0;
  const absX = dx < 0 ? -dx : dx;
  const absY = dy < 0 ? -dy : dy;
  // First-quadrant angle of the magnitude pair; the table spans [0, π/4],
  // so the steep octant mirrors around the diagonal.
  let firstQuadrant: number;
  if (absY <= absX) {
    firstQuadrant =
      ATAN_TABLE[(ratioQ16(absY, absX) / Q16_PER_ENTRY) | 0] as number;
  } else {
    const shallow =
      ATAN_TABLE[(ratioQ16(absX, absY) / Q16_PER_ENTRY) | 0] as number;
    firstQuadrant = QUARTER_TURN - shallow;
  }
  if (dx >= 0) {
    if (dy >= 0) return firstQuadrant;
    return firstQuadrant === 0 ? 0 : -firstQuadrant;
  }
  if (dy >= 0) return HALF_TURN - firstQuadrant;
  // A third-quadrant angle within half a brad of ±π canonicalises to +π,
  // never −π — the same (−π, π] rule wrapToPi enforces.
  if (firstQuadrant === 0) return HALF_TURN;
  return firstQuadrant - HALF_TURN;
}
